version: "3.0"

services:
  book-shop-app:
    build: ./
    command: ./wait-for-postgres.sh db ./book-shop-app
    ports:
    - 8090:8090
    depends_on:
    - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
  