env: "local"

db:
    username: "postgres"
    host: "db"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

http_server:
    adress: "0.0.0.0:8090"
    timeout: 4s
    idle_timeout: 60s

