env: "local"

db:
    username: "postgres"
    host: "localhost"
    port: "5436"
    dbname: "postgres"
    sslmode: "disable"
    
http_server:
    adress: "localhost:8090"
    timeout: 4s
    idle_timeout: 60s

